FROM mongo:3.6.0

# build cmd: docker build -t jager-mongo:1.0.0 .
# start cmd: docker run -p 27017:27017 -d jager-mongo:1.0.0
MAINTAINER uniray7 uniray7@gmail.com

# TODO: need add access control setting
EXPOSE 27017
