---
services:
    api:
        version: "1.0.0"
        host: localhost
        ports:
            client: "5000:5000"
    database:
        version: "mongo-3.6.0"
        db_name: jagereye-dev
        url: mongodb://localhost:27017
        ports:
            client: "27017:27017"
    messaging:
        version: "nats-1.0.4"
        host: localhost
        ports:
            client: "4222:4222"
            monitor: "8222:8222"
    mem_db:
        version: "redis-4.0.6"
        host: localhost
        ports:
            client: "6379:6379"
